# Generated by Django 2.1.7 on 2020-02-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PH_NO', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Busbooking',
                'verbose_name_plural': 'Busbookings',
            },
        ),
        migrations.CreateModel(
            name='Welcome_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.CharField(max_length=50)),
                ('TO', models.CharField(max_length=50)),
                ('BUSNAME', models.CharField(max_length=50)),
                ('BUSTIME', models.FloatField()),
            ],
            options={
                'verbose_name': 'Welcome_Form',
                'verbose_name_plural': 'Welcome_Forms',
            },
        ),
    ]
