# Generated by Django 2.1.7 on 2020-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MODELNAME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Welcome_Form',
        ),
    ]
