# Generated by Django 2.1.7 on 2020-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_auto_20200228_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.CharField(max_length=50)),
                ('TO', models.CharField(max_length=50)),
                ('BUSNAME', models.CharField(max_length=50)),
                ('BUSTIME', models.FloatField()),
            ],
            options={
                'verbose_name': 'Welcome_Form',
                'verbose_name_plural': 'Welcome_Forms',
            },
        ),
        migrations.DeleteModel(
            name='MODELNAME',
        ),
    ]
