# Generated by Django 2.1.7 on 2020-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_auto_20200303_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busbooking',
            options={'verbose_name': 'busbooking', 'verbose_name_plural': 'busbookings'},
        ),
        migrations.AlterModelOptions(
            name='welcome_form',
            options={'verbose_name': 'welcome_Form', 'verbose_name_plural': 'welcome_Forms'},
        ),
    ]
