# Generated by Django 2.1.7 on 2020-03-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_auto_20200303_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busbooking',
            options={'verbose_name': 'Busbooking', 'verbose_name_plural': 'Busbookings'},
        ),
        migrations.AlterModelOptions(
            name='welcome_form',
            options={'verbose_name': 'Welcome_Form', 'verbose_name_plural': 'Welcome_Forms'},
        ),
    ]
