# Generated by Django 2.1.7 on 2020-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_auto_20200304_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='PH_NO',
            field=models.IntegerField(max_length=10),
        ),
    ]
