# Generated by Django 2.1.7 on 2020-03-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0006_auto_20200305_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='PH_NO',
            field=models.IntegerField(),
        ),
    ]
